AMDGPU blog
Sabayon/sabayon-website-next pull request #54
Opened 2017-06-23 22:26 UTC by jcfrosty

this is my first time attempting to add to the blog. Can someone please double check my work?

2017-06-25 11:25 UTC, Ryuno-Ki requested changes
Thanks for taking time to write this article, @jcfrosty!

I found some minor bits (Most the times I commented them once, but they explain to further occurences in this text).

I request changes mainly because I would like to see more level-two-headlines (`##`), in order to help the reader grasp the content easier. As an example read only the headlines and tell me, what the content is about.

Since the topic is quite technical, you should add link to a wiki (ours or Wikipedia) for technical terms like fgrlx, DC or similiar (my personal opinion).

If you add the headlines, I approve the PR. The other changes just ease reading IMHO.

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +layer).  The old DAL was just as it sounds, an abastraction layer. This
There are two spaces after the period of the sentence concerning DAL, HAL.

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +We all remember how 'lovely' fglrx was a times with broken crossfire support,
Could you please use proper quotation marks? Like `„`, `“` or `”`?

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +be simple?" Short answer, No. They have to go over code with a fine tooth comb
Again, please use proper quotation marks: `„`, `“` and `”`.

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +code from scratch to make a native/direct communication line for the linux kernel.
Here you used a lowercase `Linux`. On purpose?

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +but let it be known this issue is affecting all Linux distributions.
Hm, I would need to think about how to interpret the phrase „let it be known” …

2017-06-25 11:25 UTC, Ryuno-Ki commented on content/article/AMDGPU_20170624.md
> +-Frosty
That line will be placed after the one above. Are you fine with that?

2017-06-26 16:25 UTC, closed without merging

2017-06-26 17:01 UTC, Ryuno-Ki commented
Hi, @jcfrosty!

Could you tell me, why you closed this PR?

2017-06-26 17:22 UTC, jcfrosty commented
I didn't? Or at least I didn't mean to? I'm trying to correct the problems
you listed currently.

On Mon, Jun 26, 2017, 12:01 PM André Jaenisch <notifications@github.com>
wrote:

> Hi, @jcfrosty <https://github.com/jcfrosty>!
>
> Could you tell me, why you closed this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sabayon/sabayon-website-next/pull/54#issuecomment-311120021>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ANERGQOis4KQjkes8M7CNZmv_c3Bac3Nks5sH-PqgaJpZM4OEGqZ>
> .
>

2017-06-26 17:35 UTC, Enlik commented on content/article/AMDGPU_20170624.md
> +* Do not support their latest graphics cards at all ,VEGA and beyond, upon release
" ,VEGA" → ", VEGA"

2017-06-26 17:35 UTC, Enlik commented on content/article/AMDGPU_20170624.md
> +Valve has also offered is services to help forward AMDGPU. [Looking forward to VR.](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-PRO-VR-Linux)
is → its

2017-06-26 17:36 UTC, Enlik commented on content/article/AMDGPU_20170624.md
> +Valve has also offered is services to help forward AMDGPU. [Looking forward to VR.](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-PRO-VR-Linux)
Try to make a note what VR is.

2017-06-26 17:37 UTC, Enlik commented on content/article/AMDGPU_20170624.md
> +* Push their team to get the DC conversion completed and submitted to the linux kernel
It could be worth to "unwind" the acronym here.

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +layer).  The old DAL was just as it sounds, an abastraction layer. This
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +We all remember how 'lovely' fglrx was a times with broken crossfire support,
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +be simple?" Short answer, No. They have to go over code with a fine tooth comb
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +code from scratch to make a native/direct communication line for the linux kernel.
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +but let it be known this issue is affecting all Linux distributions.
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +-Frosty
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +* Do not support their latest graphics cards at all ,VEGA and beyond, upon release
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +Valve has also offered is services to help forward AMDGPU. [Looking forward to VR.](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-PRO-VR-Linux)
fixed

2017-06-26 17:45 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +Valve has also offered is services to help forward AMDGPU. [Looking forward to VR.](https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-PRO-VR-Linux)
fixed

2017-06-26 17:46 UTC, jcfrosty commented on content/article/AMDGPU_20170624.md
> +* Push their team to get the DC conversion completed and submitted to the linux kernel
Fixed

2017-06-26 17:46 UTC, jcfrosty commented
Sorry for the mess. as you can tell, I'm not completely familiar with github yet. I'm learning ;) 

https://github.com/Sabayon/sabayon-website-next/pull/55

2017-06-26 17:49 UTC, Enlik commented
General comment: I enjoyed the read but my feel is that the article is more technical (due to vocabulary and style being used), I could said nerdy, and can be harder by the less technical ones, or can leave readers with less knowledge of the video/GPU ecosystem some questions.

By itself, this is not a bad thing, especially given that it's signed by your name (meaning the style /can/ be personal as I think of it), and in my option it could be left as is, but you might keep this in mind when writing futher articles on the website. (I'm not for dumbing down content; reading something like this actually allows someone to learn from it which is great, so take what I wrote with a grain of salt.)

2017-06-26 17:49 UTC, Enlik commented
> Sorry for the mess. as you can tell, I'm not completely familiar with github yet. I'm learning ;)

This one could be reopened instead, to keep everything in one place. Please do this like this in the future.

2017-06-26 17:55 UTC, Enlik commented on content/article/AMDGPU_20170624.md
> +* Push their team to get the DC conversion completed and submitted to the linux kernel
"Push their team to get the display code converted and submitted to the Linux kernel"

Better but now it reads like a generic display code (so why would it need converting?), not *that* DC stat stands next to HAL and DAL.

2017-06-26 17:56 UTC, jcfrosty commented
Glad you liked it. Yeah, I figured the only people who would be interested in the AMDGPU blog would be people with an AMD card looking for answers (both techy and non). I don't plan on them all being techy, but there are those who are upset with AMD in general and I felt they deserved some sort of explanation. Even if it was a little over the top, they could still get something out of it.

I'll keep in mind the ability to reopen next time. I was looking at the closed image at the top and looking to see if I could click it and get it to reopen, but it doesn't work that way. I just noticed the "reopen and comment" button on the bottom. I should have checked that before opening a new one.

2017-06-26 18:06 UTC, Enlik commented
Changing "radeon" to something like "the radeon driver" should make it much easier for those non-AMD device owners in the following sentence.

"Some of you may still be using radeon on 
+AMD HD7XXX or R9 2XX (SI/CIK) video cards."

2017-06-26 18:16 UTC, jcfrosty commented
Good point, also fixed.